<?php
// Installation wizard
// Access via /install – creates DB tables and first admin user.
// Blocked automatically once setup_complete = 1.

declare(strict_types=1);

// public/ is the DocumentRoot; app root is one level up
$appRoot = dirname(__DIR__);

require_once $appRoot . '/config/config.php';

$step    = (int)($_GET['step'] ?? 1);
$errors  = [];
$success = '';

// ── Helper ────────────────────────────────────────────────────────────
function tryConnect(string $host, string $port, string $db, string $user, string $pass): ?PDO {
    try {
        $pdo = new PDO(
            "mysql:host={$host};port={$port};charset=utf8mb4",
            $user, $pass,
            [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_EMULATE_PREPARES => false]
        );
        return $pdo;
    } catch (PDOException) {
        return null;
    }
}

// Check if already installed
$alreadyInstalled = false;
try {
    require_once $appRoot . '/config/database.php';
    $val = Database::getSetting('setup_complete', '0');
    if ($val === '1') $alreadyInstalled = true;
} catch (Throwable) {
    // DB not yet set up
}

if ($alreadyInstalled) {
    header('Location: ' . APP_URL . '/');
    exit;
}

// ── Step 2: Test DB + write local config ──────────────────────────────
if ($step === 2 && $_SERVER['REQUEST_METHOD'] === 'POST') {
    $dbHost = trim($_POST['db_host'] ?? 'localhost');
    $dbPort = trim($_POST['db_port'] ?? '3306');
    $dbName = trim($_POST['db_name'] ?? 'fortbildungsmanager');
    $dbUser = trim($_POST['db_user'] ?? '');
    $dbPass = $_POST['db_pass'] ?? '';
    $appUrl = rtrim(trim($_POST['app_url'] ?? ''), '/');
    $appSec = bin2hex(random_bytes(24));

    $pdo = tryConnect($dbHost, $dbPort, $dbName, $dbUser, $dbPass);
    if (!$pdo) {
        // Try creating the database
        $pdoRoot = tryConnect($dbHost, $dbPort, '', $dbUser, $dbPass);
        if ($pdoRoot) {
            $pdoRoot->exec("CREATE DATABASE IF NOT EXISTS `{$dbName}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
            $pdo = tryConnect($dbHost, $dbPort, $dbName, $dbUser, $dbPass);
        }
    }

    if (!$pdo) {
        $errors[] = 'Datenbankverbindung fehlgeschlagen. Bitte prüfen Sie Host, Port, Benutzer und Passwort.';
    } else {
        // Write local config
        $localConfig = <<<PHP
<?php
// Local configuration – generated by installer
define('DB_HOST', '{$dbHost}');
define('DB_PORT', '{$dbPort}');
define('DB_NAME', '{$dbName}');
define('DB_USER', '{$dbUser}');
define('DB_PASS', '{$dbPass}');
define('APP_URL', '{$appUrl}');
define('APP_SECRET', '{$appSec}');
PHP;
        $localFile = $appRoot . '/config/local.php';
        if (file_put_contents($localFile, $localConfig) === false) {
            $errors[] = 'config/local.php konnte nicht geschrieben werden. Bitte prüfen Sie die Schreibrechte: chmod 775 /var/www/fobi/config';
        } else {
            chmod($localFile, 0640); // owner rw, group r, others nothing
            header('Location: ' . $appUrl . '/install?step=3');
            exit;
        }
    }
}

// ── Step 3: Import schema ─────────────────────────────────────────────
if ($step === 3) {
    try {
        require_once $appRoot . '/config/database.php';
        $sql = file_get_contents($appRoot . '/sql/schema.sql');
        // Split by semicolon, execute each statement
        $statements = array_filter(array_map('trim', explode(';', $sql)));
        $pdo        = Database::getInstance();
        foreach ($statements as $stmt) {
            if ($stmt) $pdo->exec($stmt);
        }
        $success = 'Datenbank-Schema erfolgreich importiert.';
        $step    = 4;
    } catch (Throwable $e) {
        $errors[] = 'Fehler beim Importieren: ' . $e->getMessage();
    }
}

// ── Step 4: Create admin user ──────────────────────────────────────────
if ($step === 4 && $_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['create_admin'])) {
    require_once $appRoot . '/config/database.php';
    $adminEmail  = strtolower(trim($_POST['admin_email'] ?? ''));
    $adminName   = trim($_POST['admin_name'] ?? '');
    $domain      = substr($adminEmail, strrpos($adminEmail, '@') + 1);
    $appName     = trim($_POST['app_name'] ?? 'Fortbildungsmanager');

    if (!filter_var($adminEmail, FILTER_VALIDATE_EMAIL)) {
        $errors[] = 'Bitte geben Sie eine gültige E-Mail-Adresse ein.';
    } else {
        // Save app settings
        Database::setSetting('app_name',     $appName);
        Database::setSetting('app_url',      APP_URL);
        Database::setSetting('admin_email',  $adminEmail);
        Database::setSetting('mail_from',    $adminEmail);
        Database::setSetting('mail_from_name', $appName);

        // Add domain as auto-approved
        Database::execute(
            'INSERT INTO `allowed_domains` (`domain`, `auto_approved`) VALUES (?, 1)
             ON DUPLICATE KEY UPDATE `auto_approved` = 1',
            [$domain]
        );

        // Create or update admin user
        $existing = Database::fetchOne('SELECT id FROM `users` WHERE `email` = ?', [$adminEmail]);
        if ($existing) {
            Database::execute(
                'UPDATE `users` SET `name` = ?, `role` = "admin", `status` = "active" WHERE `id` = ?',
                [$adminName, $existing['id']]
            );
        } else {
            Database::execute(
                'INSERT INTO `users` (`email`, `name`, `role`, `status`) VALUES (?, ?, "admin", "active")',
                [$adminEmail, $adminName]
            );
        }

        Database::setSetting('setup_complete', '1');
        $step = 5; // Done
    }
}

// ── HTML output ────────────────────────────────────────────────────────
$currentStep = $step;
?>
<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Installation – Fortbildungsmanager</title>
  <link rel="stylesheet" href="<?= APP_URL ?>/assets/css/style.css">
  <style>
    body { background: #f0f4f8; }
    .install-wrap { max-width: 560px; margin: 60px auto; padding: 0 16px; }
    .steps { display: flex; gap: 4px; margin-bottom: 28px; counter-reset: step; }
    .step-dot {
      flex: 1; text-align: center; padding: 8px 4px;
      border-radius: 4px; font-size: .82rem; font-weight: 600;
      background: #e9ecef; color: #6c757d;
      counter-increment: step;
    }
    .step-dot::before { content: counter(step) '. '; }
    .step-dot.active { background: #1a6fb5; color: #fff; }
    .step-dot.done   { background: #28a745; color: #fff; }
  </style>
</head>
<body>
<div class="install-wrap">
  <h1 style="text-align:center;margin-bottom:8px">Fortbildungsmanager</h1>
  <p style="text-align:center;color:#6c757d;margin-bottom:24px">Installationsassistent</p>

  <div class="steps">
    <div class="step-dot <?= $currentStep >= 1 ? ($currentStep > 1 ? 'done' : 'active') : '' ?>">Start</div>
    <div class="step-dot <?= $currentStep >= 2 ? ($currentStep > 2 ? 'done' : 'active') : '' ?>">Datenbank</div>
    <div class="step-dot <?= $currentStep >= 3 ? ($currentStep > 3 ? 'done' : 'active') : '' ?>">Schema</div>
    <div class="step-dot <?= $currentStep >= 4 ? ($currentStep > 4 ? 'done' : 'active') : '' ?>">Admin</div>
    <div class="step-dot <?= $currentStep >= 5 ? 'done' : '' ?>">Fertig</div>
  </div>

  <?php foreach ($errors as $e): ?>
    <div class="alert alert-error"><?= htmlspecialchars($e) ?></div>
  <?php endforeach; ?>
  <?php if ($success): ?>
    <div class="alert alert-success"><?= htmlspecialchars($success) ?></div>
  <?php endif; ?>

  <?php if ($currentStep === 1): ?>
    <div class="card">
      <h2>Willkommen</h2>
      <p>Dieser Assistent richtet den Fortbildungsmanager ein. Sie benötigen:</p>
      <ul>
        <li>PHP 8.1+ mit PDO-MySQL-Erweiterung</li>
        <li>MariaDB / MySQL Datenbankzugang</li>
        <li>Apache2 mit <code>mod_rewrite</code></li>
      </ul>
      <p>Bitte stellen Sie sicher, dass das Verzeichnis <code>config/</code> (eine Ebene über <code>public/</code>) für den Webserver schreibbar ist,
         damit <code>config/local.php</code> angelegt werden kann.</p>
      <a href="?step=2" class="btn btn-primary">Weiter</a>
    </div>

  <?php elseif ($currentStep === 2): ?>
    <div class="card">
      <h2>Datenbankverbindung</h2>
      <form method="post" action="?step=2" class="form">
        <div class="form-row">
          <div class="form-group">
            <label>Host</label>
            <input type="text" name="db_host" value="<?= htmlspecialchars($_POST['db_host'] ?? 'localhost') ?>" required>
          </div>
          <div class="form-group">
            <label>Port</label>
            <input type="number" name="db_port" value="<?= htmlspecialchars($_POST['db_port'] ?? '3306') ?>" required>
          </div>
        </div>
        <div class="form-group">
          <label>Datenbankname</label>
          <input type="text" name="db_name" value="<?= htmlspecialchars($_POST['db_name'] ?? 'fortbildungsmanager') ?>" required>
          <small>Wird angelegt, falls noch nicht vorhanden.</small>
        </div>
        <div class="form-row">
          <div class="form-group">
            <label>Datenbankbenutzer</label>
            <input type="text" name="db_user" value="<?= htmlspecialchars($_POST['db_user'] ?? '') ?>" required>
          </div>
          <div class="form-group">
            <label>Passwort</label>
            <input type="password" name="db_pass" autocomplete="new-password">
          </div>
        </div>
        <div class="form-group">
          <label>Basis-URL der Anwendung</label>
          <input type="url" name="app_url" value="<?= htmlspecialchars($_POST['app_url'] ?? APP_URL) ?>" required
                 placeholder="https://fobi.meinedomain.de">
          <small>Subdomain ohne abschließenden Schrägstrich, z.B. <code>https://fobi.meinedomain.de</code></small>
        </div>
        <button type="submit" class="btn btn-primary">Verbindung testen & weiter</button>
      </form>
    </div>

  <?php elseif ($currentStep === 3): ?>
    <div class="card">
      <h2>Datenbank-Schema</h2>
      <p>Alle Tabellen wurden erfolgreich angelegt. Weiter mit dem Administratorkonto.</p>
      <a href="?step=4" class="btn btn-primary">Weiter</a>
    </div>

  <?php elseif ($currentStep === 4): ?>
    <div class="card">
      <h2>Administrator einrichten</h2>
      <form method="post" action="?step=4" class="form">
        <div class="form-group">
          <label>Anwendungsname</label>
          <input type="text" name="app_name" value="Fortbildungsmanager" required>
        </div>
        <div class="form-group">
          <label>Admin E-Mail</label>
          <input type="email" name="admin_email" required placeholder="admin@schule.de">
          <small>Die Domain wird automatisch als zugelassene Domain eingetragen.</small>
        </div>
        <div class="form-group">
          <label>Admin Name (optional)</label>
          <input type="text" name="admin_name" placeholder="Vor- und Nachname">
        </div>
        <button type="submit" name="create_admin" value="1" class="btn btn-primary">Installation abschließen</button>
      </form>
    </div>

  <?php elseif ($currentStep === 5): ?>
    <div class="card" style="text-align:center">
      <div style="font-size:3rem;margin-bottom:12px">✓</div>
      <h2>Installation abgeschlossen!</h2>
      <p>Der Fortbildungsmanager ist betriebsbereit.</p>
      <p>Melden Sie sich mit Ihrer Admin-E-Mail-Adresse an, um einen Magic-Link zu erhalten.</p>
      <a href="<?= APP_URL ?>/login" class="btn btn-primary" style="margin-top:8px">Zur Anmeldung</a>
    </div>
  <?php endif; ?>
</div>
</body>
</html>
